"""create_ai_analysis_table

Revision ID: 021f0b7ed848
Revises: 
Create Date: 2026-07-15 17:57:04.353180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '021f0b7ed848'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='기본 키'),
    sa.Column('is_pneumonia', sa.Boolean(), nullable=False, comment='폐렴 진단 여부'),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=False, comment='AI 예측 확률'),
    sa.Column('heatmap_url', sa.String(length=255), nullable=False, comment='AI 분석 결과 이미지 경로'),
    sa.Column('ai_model', sa.String(length=50), nullable=False, comment='AI 예측 모델명'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='생성 일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='수정 일시'),
    sa.PrimaryKeyConstraint('id'),
    comment='AI 분석 결과 저장 테이블'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_analysis_results')
    # ### end Alembic commands ###
