"""create initial tables

Revision ID: 11abd37a7ee7
Revises: 
Create Date: 2026-07-15 23:16:41.534171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11abd37a7ee7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='기본 키'),
    sa.Column('is_pneumonia', sa.Boolean(), nullable=False, comment='폐렴 진단 여부'),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=False, comment='AI 예측 확률'),
    sa.Column('heatmap_url', sa.String(length=255), nullable=False, comment='AI 분석 결과 이미지 경로'),
    sa.Column('ai_model', sa.String(length=50), nullable=False, comment='AI 예측 모델명'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='수정 일시'),
    sa.PrimaryKeyConstraint('id'),
    comment='AI 분석 결과 저장 테이블'
    )
    op.create_table('patients',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False, comment='환자 성명'),
    sa.Column('age', sa.SmallInteger(), nullable=False, comment='나이'),
    sa.Column('gender', sa.Enum('M', 'F', name='gender'), nullable=True, comment='환자 성별'),
    sa.Column('phone', sa.String(length=11), nullable=False, comment='환자 연락처, 국내 전화번호로 한정'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='환자 정보 등록 일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='환자 정보 수정 일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True, comment='평문 저장 x -> 해쉬화 된 비밀번호 저장'),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True, comment='유저 휴대폰 번호'),
    sa.Column('gender', sa.Enum('M', 'F', name='gender'), nullable=False, comment='성별 선택'),
    sa.Column('department', sa.Enum('MEDICAL', 'DEV', 'RESEARCH', name='department'), nullable=False, comment='부서 선택'),
    sa.Column('role', sa.Enum('PENDING', 'STAFF', 'ADMIN', name='role'), nullable=False, comment='부여된 역할 권한'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False, comment='계정 활성화 여부'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='유저 생성 일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='유저 정보 수정 일시'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('medical_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('chart_number', sa.String(length=50), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chart_number')
    )
    op.create_table('xray_images',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.BigInteger(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=False),
    sa.Column('shooting_datetime', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['medical_records.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xray_images_record_id'), 'xray_images', ['record_id'], unique=False)
    op.create_index(op.f('ix_xray_images_uploader_id'), 'xray_images', ['uploader_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xray_images_uploader_id'), table_name='xray_images')
    op.drop_index(op.f('ix_xray_images_record_id'), table_name='xray_images')
    op.drop_table('xray_images')
    op.drop_table('medical_records')
    op.drop_table('users')
    op.drop_table('patients')
    op.drop_table('ai_analysis_results')
    # ### end Alembic commands ###
