"""add role column to user

Revision ID: 36a3463d89e0
Revises: bf264bb97c61
Create Date: 2026-07-16 16:49:41.420099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '36a3463d89e0'
down_revision: Union[str, Sequence[str], None] = 'bf264bb97c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('PENDING', 'STAFF', 'ADMIN'),
               type_=sa.String(length=20),
               nullable=True,
               comment=None,
               existing_comment='부여된 역할 권한')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('PENDING', 'STAFF', 'ADMIN'),
               nullable=False,
               comment='부여된 역할 권한')
    # ### end Alembic commands ###
