"""Auto migration

Revision ID: 4bbe9a74d096
Revises: 31f139297e98
Create Date: 2026-07-15 21:42:55.796664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4bbe9a74d096'
down_revision: Union[str, Sequence[str], None] = '31f139297e98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('phone_number'), table_name='users')
    op.drop_table('users')
    op.drop_table('patients')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=False, comment='환자 성명'),
    sa.Column('age', mysql.SMALLINT(), autoincrement=False, nullable=False, comment='smallint'),
    sa.Column('gender', mysql.ENUM('M', 'F'), nullable=True, comment='환자 성별'),
    sa.Column('phone', mysql.VARCHAR(length=11), nullable=False, comment='환자 연락처, 국내 전화번호로 한정'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False, comment='환자 정보 등록 일시'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True, comment='환자 정보 수정 일시'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('gender', mysql.ENUM('M', 'F'), nullable=False, comment='성별 선택'),
    sa.Column('department', mysql.ENUM('MEDICAL', 'DEV', 'RESEARCH'), nullable=False, comment='부서 선택'),
    sa.Column('role', mysql.ENUM('PENDING', 'STAFF', 'ADMIN'), nullable=False, comment='부여된 역할 권한'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='계정 활성화 여부'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False, comment='유저 생성 일시'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True, comment='유저 정보 수정 일시'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
