"""add medical record relationships

Revision ID: bf264bb97c61
Revises: 11abd37a7ee7
Create Date: 2026-07-15 23:56:54.530556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bf264bb97c61'
down_revision: Union[str, Sequence[str], None] = '11abd37a7ee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_analysis_results', sa.Column('record_id', sa.BigInteger(), nullable=False, comment='진료 기록 ID'))
    op.alter_column('ai_analysis_results', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='생성 일시',
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('ai_analysis_results', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='수정 일시',
               existing_nullable=True)
    op.create_foreign_key(None, 'ai_analysis_results', 'medical_records', ['record_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_analysis_results', type_='foreignkey')
    op.alter_column('ai_analysis_results', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='수정 일시',
               existing_nullable=True)
    op.alter_column('ai_analysis_results', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='생성 일시',
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_column('ai_analysis_results', 'record_id')
    # ### end Alembic commands ###
