"""Auto migration

Revision ID: e7cf78a91706
Revises: 36a3463d89e0
Create Date: 2026-07-21 18:02:49.738133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = 'e7cf78a91706'
down_revision: Union[str, Sequence[str], None] = '36a3463d89e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_analysis_results', 'confidence',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='AI 예측 신뢰도',
               existing_comment='AI 예측 확률',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'STAFF', 'ADMIN', name='role'),
               nullable=False,
               comment='부여된 역할 권한')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('PENDING', 'STAFF', 'ADMIN', name='role'),
               type_=mysql.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='부여된 역할 권한')
    op.alter_column('ai_analysis_results', 'confidence',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='AI 예측 확률',
               existing_comment='AI 예측 신뢰도',
               existing_nullable=False)
    # ### end Alembic commands ###
